TG_Bots/TEST_DJ/VINYLON/VINYLON/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='main')),
    path('catalog/', include('catalogue.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='auth')),
    path("orders/", include("orders.urls"), name="orders"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TG_Bots/TEST_DJ/VINYLON/catalogue/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "catalog"

urlpatterns = [
    path('', views.CatalogueView.as_view(), name="cata"),
]

TG_Bots/TEST_DJ/VINYLON/home/urls.py
from django.urls import path
from .views import HomePageView, SearchResultsView
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'main'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('about/', views.about, name='about'),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TG_Bots/TEST_DJ/VINYLON/orders/urls.py
from django.urls import path
from .views import OrderListView, OrderDetailView, CreateOrderView

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='order_list'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order_detail'),
    path('create/', CreateOrderView.as_view(), name='order_create'),
]

TG_Bots/TEST_DJ/VINYLON/users/urls.py
from django.urls import path
from .views import UserProfileView, UserLoginView, RegisterView, UserLogoutView, UserPasswordChangeView

app_name = 'auth'

urlpatterns = [
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('change-password/', UserPasswordChangeView.as_view(), name='change_password'),
]

TG_Bots/TEST_DJ/VINYLON/home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from catalogue.models import VinylRecord, Tag, Artist
from orders.models import Order
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, Count

class HomePageView(ListView):
    model = VinylRecord
    template_name = 'home/index.html'
    context_object_name = 'vinyls'
    paginate_by = 10
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Отображение топ-10 тегов
        context['top_tags'] = Tag.objects.annotate(num_records=Count('records')).order_by('-num_records')[:10]
        # Отображение заказов для авторизованных пользователей
        if self.request.user.is_authenticated:
            context['orders'] = Order.objects.filter(user=self.request.user)
        context['artists'] = Artist.objects.all() 
        context['vinyl_records'] = VinylRecord.objects.all().order_by("-release_date")


        return context


class SearchResultsView(ListView):
    model = VinylRecord
    template_name = "home/search_results.html"
    context_object_name = "vinyls"

    def get_queryset(self):
        query = self.request.GET.get("query")
        return VinylRecord.objects.filter(
            Q(title__icontains=query) | Q(artist__icontains=query)
        )



# def home(request):
#     context: dict[str, str] = {
#         'title': 'Home - Главная',
#         'content_1': 'Музыкальная площадка',
#         'content_2': 'VINYLON',
#     }

#     return render(request, 'home/index.html', context)

def about(request):
    context: dict[str, str] = {
        'title': 'Home - О нас',
        'content_1': 'О нас',
        'content_2': 'Интернет магазин виниловых пластинок и музыкальная площадка',
    }

    return render(request, 'home/about.html', context)

TG_Bots/TEST_DJ/VINYLON/home/templates/home/about.html
{% extends "home/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
{% endblock %}

{% block content %}
    <h1 class="mt-5 pt-5"><strong>{{ content_1 }}</strong></h1>
    <p><span style="color: white;">{{ content_2 }}</span></p>
{% endblock  %}

{% block footer %}
<footer class="py-4 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2024</p>
    </div>
</footer>
{% endblock  %}

TG_Bots/TEST_DJ/VINYLON/home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href= "{% static 'deps/css/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}">
    <!-- Стиль footer-a для главной страницы -->
    {% block css %}{% endblock  %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'deps/favicon/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'deps/favicon/icon32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'deps/favicon/icon16x16.png' %}">
    <link rel="manifest" href="{% static 'deps/favicon/site.webmanifest' %}">
    <title>{{ title }}</title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li><a class="nav-link dropdown-toggle text-white" href="{% url 'main:home' %}">Главная</a></li>
                        <li><a class="nav-link dropdown-toggle text-white" href="{% url 'catalog:cata' %}">Каталог</a></li>
                        <li><a class="nav-link dropdown-toggle text-white" href="{% url 'orders:order_list' %}">Мои заказы</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="nav-link dropdown-toggle text-white" href="{% url 'auth:profile' %}">Профиль</a></li>
                            <li>
                                <form method="post" action="{% url 'auth:logout' %}">
                                    {% csrf_token %}
                                    <button class="btn btn-link nav-link text-white" type="submit">Выйти</button>
                                </form>
                            </li>
                        {% else %}
                            <li><a class="nav-link dropdown-toggle text-white" href="{% url 'auth:login' %}">Войти</a></li>
                        {% endif %}
                    </ul>
                    <form class="d-flex" method="get" action="{% url 'main:search_results' %}" class="search-form">
                        <input class="form-control me-2" type="text" name="query" placeholder="Поиск...">
                        <button class="btn btn-outline-success text-white" type="submit">Найти</button>
                    </form>
                </div>
            </div>
        </nav>
        {% comment %} <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="#">Доставка и оплата</a></li>
                                <li><a class="dropdown-item  text-white" href="#">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'main:about' %}">О нас</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="carts/cart.html">Корзина</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  text-white" href="{% url 'auth:login' %}">Войти</a>
                        </li>
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Мой профиль
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="carts/cart.html">Корзина</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'auth:user_profile' %}">Личный кабинет</a>
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Админ панель</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item  text-white" href="#">Выйти</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav> {% endcomment %}
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
            {% comment %} <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static 'deps/icons/grid-fill.svg' %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>
                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        <li><a class="dropdown-item text-white" href="{% url 'catalog:cata' %}">Все товары</a></li>
                        <li><a class="dropdown-item text-white" href="{% url 'catalog:cata' %}">Кухня</a></li>
                        <li><a class="dropdown-item text-white" href="{% url 'catalog:cata' %}">Спальня</a></li>
                        <li><a class="dropdown-item text-white" href="{% url 'catalog:cata' %}">Гостинная</a></li>
                        <li><a class="dropdown-item text-white" href="{% url 'catalog:cata' %}">Офис</a></li>
                        <li><a class="dropdown-item text-white" href="{% url 'catalog:cata' %}">Фурнитура</a></li>
                        <li><a class="dropdown-item text-white" href="{% url 'catalog:cata' %}">Декор</a></li>
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                <div>
                    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
                        aria-expanded="false">
                        <img class="mx-1" src="{% static 'deps/icons/basket2-fill.svg' %}" alt="Catalog Icon" width="24"
                            height="24">
                        <span id="goods-in-cart-count">0</span>
                    </button>
                </div>
                <!-- Разметка модального окна корзины -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <h3 class="text-center mb-4">Корзина</h3>
                                <div class="container" id="cart-items-container">
                                    <!-- Разметка корзины -->
                                    <div class="card mb-3 text-bg-light shadow-lg">
                                        <div class="card-header">
                                            <h5 class="card-title">Товар</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">
                                                <div class="row text-center">
                                                    <div class="col p-0">
                                                        <div class="input-group">
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm decrement"
                                                                    data-cart-id="" data-cart-change-url="">-</button>
                                                            </span>
                                                            <input type="text" class="form-control number" value="1"
                                                                readonly>
                                                            <span class="input-group-btn">
                                                                <button type="button" class="btn btn-dark btn-sm increment"
                                                                    data-cart-id="" data-cart-change-url="">+</button>
                                                            </span>
                                                        </div>
                                                    </div>
                                                    <div class="col p-0">
                                                        <p>x 100.00 = </p>
                                                    </div>
                                                    <div class="col p-0"><strong>100.00 $</strong></div>
                                                    <div class="col p-0">
                                                        <a href="#" class="remove-from-cart" data-cart-id="">
                                                            <img class="mx-1" src="{% static 'deps/icons/trash3-fill.svg' %}"
                                                                alt="Catalog Icon" width="16" height="16">
                                                        </a>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                    <div class="card mb-3 shadow-lg">
                                        <div class="card-footer">
                                            <p class="float-left">Итого <strong>1</strong> товар(а) на сумму</p>
                                            <h4 class="float-left"><strong>100.00 $</strong></h4>
                                        </div>
                                    </div>
                                    <!-- Закончилась разметка корзины -->
                                </div>
                                <a class="btn btn-dark" href="orders/create_order.html">
                                    Оформить заказ
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Закончилась разметка модального окна -->
            </div> {% endcomment %}
        </div>
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    
                    {% block content %}{% endblock  %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}{% endblock %}
    <script src="{% static 'deps/js/jquery/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'deps/js/jquery-events.js' %}"></script>
    <script src="{% static 'deps/js/jquery-ajax.js' %}"></script>
    <script src="{% static 'deps/js/bootstrap/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

TG_Bots/TEST_DJ/VINYLON/home/templates/home/index.html
{% extends "home/base.html" %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'deps/css/my_footer_css.css' %}">
    <link rel="stylesheet" href="{% static 'deps/css/my_css.css' %}"> <!-- Подключаем новый CSS файл -->
{% endblock %}

{% block content %}
    <div class="container mt-1">
        <div class="main-content">
            <h2 class="mb-2">Артисты</h2>
            <div class="card-container">
                {% for artist in artists %}
                  <div class="card bg-dark text-white custom-shadow">
                    {% if artist.pfp %}
                      <img src="{{ artist.pfp.url }}" class="card-img-top rounded-circle" alt="{{ artist.name }}">
                    {% else %}
                      <img src="{% static 'default_artist.jpg' %}" class="card-img-top rounded-circle" alt="Default Artist">
                    {% endif %}
                    <div class="card-body">
                      <h5 class="card-title">{{ artist.name }}</h5>
                      <p class="card-text">{{ artist.major_info }}</p>
                    </div>
                  </div>
                {% endfor %}
              </div>

            <h2 class="mb-2">Пластинки</h2>
            <div class="card-container">
                    {% for vinyl in vinyl_records %}
                            <div class="card bg-dark text-white custom-shadow">
                                <img src="{{ vinyl.cover.url }}" class="card-img-top rounded-circle mx-auto" style="width: 110px; height: 100px;">
                                <div class="card-body p-1">
                                    <p class="title">{{ vinyl.title }}</p>
                                    <p class="price">{{ vinyl.price }} $</p>
                                </div>
                            </div>
                    {% endfor %}
            </div>
                
            <h2 class="mb-4">Горячие новинки</h2>
            <div class="row">
                {% for item in hot_new_items|slice:":5" %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.title }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.title }}</h5>
                                <p class="card-text">{{ item.description }}</p>
                                <p class="card-text"><strong>{{ item.price }} $</strong></p>
                                <a href="{% url 'catalog:item_detail' item.id %}" class="btn btn-primary">Купить</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <h2 class="mb-4">Горячие скидки</h2>
            <div class="row">
                {% for item in hot_discount_items|slice:":5" %}
                    <div class="col-md-4 mb-4">
                        <div class="card">
                            <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.title }}">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.title }}</h5>
                                <p class="card-text">{{ item.description }}</p>
                                <p class="card-text">
                                    <strong>
                                        <del>{{ item.original_price }} $</del> {{ item.discounted_price }} $
                                    </strong>
                                </p>
                                <a href="{% url 'catalog:item_detail' item.id %}" class="btn btn-danger">Купить со скидкой</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="container">
            <div class="playlist-container">
                <h3 class="playlist-title">Плейлист</h3>
                <div class="playlist">
                    <ul>
                        <li class="track-item" data-audio="track1.mp3">
                            <span class="track-title">Трек 1</span>
                            <span class="track-artist">Исполнитель 1</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 2</span>
                            <span class="track-artist">Исполнитель 2</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 3</span>
                            <span class="track-artist">Исполнитель 4</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 4</span>
                            <span class="track-artist">Исполнитель 4</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 5</span>
                            <span class="track-artist">Исполнитель 5</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 6</span>
                            <span class="track-artist">Исполнитель 6</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 7</span>
                            <span class="track-artist">Исполнитель 7</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 8</span>
                            <span class="track-artist">Исполнитель 8</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 9</span>
                            <span class="track-artist">Исполнитель 9</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 10</span>
                            <span class="track-artist">Исполнитель 10</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 11</span>
                            <span class="track-artist">Исполнитель 11</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 12</span>
                            <span class="track-artist">Исполнитель 12</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 13</span>
                            <span class="track-artist">Исполнитель 13</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 14</span>
                            <span class="track-artist">Исполнитель 14</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 15</span>
                            <span class="track-artist">Исполнитель 15</span>
                        </li>
                        <li class="track-item" data-audio="track2.mp3">
                            <span class="track-title">Трек 16</span>
                            <span class="track-artist">Исполнитель 16</span>
                        </li>
                        <!-- Добавьте другие треки по необходимости -->
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="pagination">
        {% if is_pagination %}
            <!-- Логика для пагинации здесь -->
        {% endif %}
    </div>
{% endblock %}

TG_Bots/TEST_DJ/VINYLON/home/templates/home/nav.html
{% extends 'home/base.html' %}
{% block content %}
<div class="main-content">
<!-- Боковая панель для авторизованных пользователей -->
<div class="sidebar">
{% if user.is_authenticated %}
<h2>Профиль</h2>
<p>Имя: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<h3>Мои заказы</h3>
<ul>
{% for order in orders %}
<li>Заказ #{{ order.id }} - {{ order.created_at }}</li>
{% empty %}
<li>У вас нет заказов</li>
{% endfor %}
</ul>
{% else %}
<p>Войдите в систему, чтобы увидеть ваши заказы.</p>
{% endif %}
</div>
<!-- Список виниловых пластинок -->
<div class="vinyl-list">
<h2>Каталог виниловых пластинок</h2>
{% for vinyl in vinyls %}
<div class="vinyl-item">
<h3>{{ vinyl.title }}</h3>
<p>Исполнитель: {{ vinyl.artist }}</p>
<p class="price">{{ vinyl.price }} $</p>
</div>
{% empty %}
<p>Пластинки не найдены.</p>
{% endfor %}
<!-- Пагинация -->
<div class="pagination">
{% if is_paginated %}
<span class="step-links">
{% if page_obj.has_previous %}
<a href="?page=1">&laquo; первая</a>
<a href="?page={{ page_obj.previous_page_number }}">предыдущая</a>
{% endif %}
<span class="current">
Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
</span>
{% if page_obj.has_next %}
<a href="?page={{ page_obj.next_page_number }}">следующая</a>
<a href="?page={{ page_obj.paginator.num_pages }}">последняя &raquo;</a>
{% endif %}
</span>
{% endif %}
</div>
</div>
</div>
<!-- Отображение топ-10 тегов -->
<div class="tags">
<h3>Топ 10 тегов</h3>
<ul>
{% for tag in top_tags %}
<li><a href="#">{{ tag.name }} ({{ tag.num_records }})</a></li>
{% empty %}
<li>Теги не найдены.</li>
{% endfor %}
</ul>
</div>
{% endblock %}

TG_Bots/TEST_DJ/VINYLON/home/templates/home/search_results.html
{% extends "home/base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Результат поиска" %}{% endblock  %}

{% block content %}
    <h1>Результаты поиска</h1>

    {% if vinyls %}
        <ul>
            {% for vinyls in vinyls %}
                <li>{{vinyl.title}} - {{vinyl.title}} - {{vinyl.title}} $</li>
            {% endfor %}
        <ul>   
    {% else %}
            <p>Ничего не найдено</p>
    {% endif %}

{% endblock  %}